// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"sqlent/ent/predicate"
	"sqlent/ent/user"
	"sqlent/ent/usercount"
	"sync"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeUser      = "User"
	TypeUserCount = "UserCount"
)

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op            Op
	typ           string
	id            *int64
	phone         *string
	password      *string
	p_id          *int
	addp_id       *int
	invited_code  *string
	created       *int64
	addcreated    *int64
	updated       *int64
	addupdated    *int64
	deleted       *int64
	adddeleted    *int64
	clearedFields map[string]struct{}
	count         map[int]struct{}
	removedcount  map[int]struct{}
	clearedcount  bool
	done          bool
	oldValue      func(context.Context) (*User, error)
	predicates    []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id int64) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of User entities.
func (m *UserMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID
// is only available if it was provided to the builder.
func (m *UserMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetPhone sets the "phone" field.
func (m *UserMutation) SetPhone(s string) {
	m.phone = &s
}

// Phone returns the value of the "phone" field in the mutation.
func (m *UserMutation) Phone() (r string, exists bool) {
	v := m.phone
	if v == nil {
		return
	}
	return *v, true
}

// OldPhone returns the old "phone" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPhone(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldPhone is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldPhone requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPhone: %w", err)
	}
	return oldValue.Phone, nil
}

// ResetPhone resets all changes to the "phone" field.
func (m *UserMutation) ResetPhone() {
	m.phone = nil
}

// SetPassword sets the "password" field.
func (m *UserMutation) SetPassword(s string) {
	m.password = &s
}

// Password returns the value of the "password" field in the mutation.
func (m *UserMutation) Password() (r string, exists bool) {
	v := m.password
	if v == nil {
		return
	}
	return *v, true
}

// OldPassword returns the old "password" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPassword(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldPassword is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldPassword requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPassword: %w", err)
	}
	return oldValue.Password, nil
}

// ResetPassword resets all changes to the "password" field.
func (m *UserMutation) ResetPassword() {
	m.password = nil
}

// SetPID sets the "p_id" field.
func (m *UserMutation) SetPID(i int) {
	m.p_id = &i
	m.addp_id = nil
}

// PID returns the value of the "p_id" field in the mutation.
func (m *UserMutation) PID() (r int, exists bool) {
	v := m.p_id
	if v == nil {
		return
	}
	return *v, true
}

// OldPID returns the old "p_id" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldPID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldPID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPID: %w", err)
	}
	return oldValue.PID, nil
}

// AddPID adds i to the "p_id" field.
func (m *UserMutation) AddPID(i int) {
	if m.addp_id != nil {
		*m.addp_id += i
	} else {
		m.addp_id = &i
	}
}

// AddedPID returns the value that was added to the "p_id" field in this mutation.
func (m *UserMutation) AddedPID() (r int, exists bool) {
	v := m.addp_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetPID resets all changes to the "p_id" field.
func (m *UserMutation) ResetPID() {
	m.p_id = nil
	m.addp_id = nil
}

// SetInvitedCode sets the "invited_code" field.
func (m *UserMutation) SetInvitedCode(s string) {
	m.invited_code = &s
}

// InvitedCode returns the value of the "invited_code" field in the mutation.
func (m *UserMutation) InvitedCode() (r string, exists bool) {
	v := m.invited_code
	if v == nil {
		return
	}
	return *v, true
}

// OldInvitedCode returns the old "invited_code" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldInvitedCode(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldInvitedCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldInvitedCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInvitedCode: %w", err)
	}
	return oldValue.InvitedCode, nil
}

// ResetInvitedCode resets all changes to the "invited_code" field.
func (m *UserMutation) ResetInvitedCode() {
	m.invited_code = nil
}

// SetCreated sets the "created" field.
func (m *UserMutation) SetCreated(i int64) {
	m.created = &i
	m.addcreated = nil
}

// Created returns the value of the "created" field in the mutation.
func (m *UserMutation) Created() (r int64, exists bool) {
	v := m.created
	if v == nil {
		return
	}
	return *v, true
}

// OldCreated returns the old "created" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldCreated(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldCreated is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldCreated requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreated: %w", err)
	}
	return oldValue.Created, nil
}

// AddCreated adds i to the "created" field.
func (m *UserMutation) AddCreated(i int64) {
	if m.addcreated != nil {
		*m.addcreated += i
	} else {
		m.addcreated = &i
	}
}

// AddedCreated returns the value that was added to the "created" field in this mutation.
func (m *UserMutation) AddedCreated() (r int64, exists bool) {
	v := m.addcreated
	if v == nil {
		return
	}
	return *v, true
}

// ResetCreated resets all changes to the "created" field.
func (m *UserMutation) ResetCreated() {
	m.created = nil
	m.addcreated = nil
}

// SetUpdated sets the "updated" field.
func (m *UserMutation) SetUpdated(i int64) {
	m.updated = &i
	m.addupdated = nil
}

// Updated returns the value of the "updated" field in the mutation.
func (m *UserMutation) Updated() (r int64, exists bool) {
	v := m.updated
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdated returns the old "updated" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldUpdated(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldUpdated is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldUpdated requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdated: %w", err)
	}
	return oldValue.Updated, nil
}

// AddUpdated adds i to the "updated" field.
func (m *UserMutation) AddUpdated(i int64) {
	if m.addupdated != nil {
		*m.addupdated += i
	} else {
		m.addupdated = &i
	}
}

// AddedUpdated returns the value that was added to the "updated" field in this mutation.
func (m *UserMutation) AddedUpdated() (r int64, exists bool) {
	v := m.addupdated
	if v == nil {
		return
	}
	return *v, true
}

// ResetUpdated resets all changes to the "updated" field.
func (m *UserMutation) ResetUpdated() {
	m.updated = nil
	m.addupdated = nil
}

// SetDeleted sets the "deleted" field.
func (m *UserMutation) SetDeleted(i int64) {
	m.deleted = &i
	m.adddeleted = nil
}

// Deleted returns the value of the "deleted" field in the mutation.
func (m *UserMutation) Deleted() (r int64, exists bool) {
	v := m.deleted
	if v == nil {
		return
	}
	return *v, true
}

// OldDeleted returns the old "deleted" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldDeleted(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldDeleted is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldDeleted requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeleted: %w", err)
	}
	return oldValue.Deleted, nil
}

// AddDeleted adds i to the "deleted" field.
func (m *UserMutation) AddDeleted(i int64) {
	if m.adddeleted != nil {
		*m.adddeleted += i
	} else {
		m.adddeleted = &i
	}
}

// AddedDeleted returns the value that was added to the "deleted" field in this mutation.
func (m *UserMutation) AddedDeleted() (r int64, exists bool) {
	v := m.adddeleted
	if v == nil {
		return
	}
	return *v, true
}

// ResetDeleted resets all changes to the "deleted" field.
func (m *UserMutation) ResetDeleted() {
	m.deleted = nil
	m.adddeleted = nil
}

// AddCountIDs adds the "count" edge to the UserCount entity by ids.
func (m *UserMutation) AddCountIDs(ids ...int) {
	if m.count == nil {
		m.count = make(map[int]struct{})
	}
	for i := range ids {
		m.count[ids[i]] = struct{}{}
	}
}

// ClearCount clears the "count" edge to the UserCount entity.
func (m *UserMutation) ClearCount() {
	m.clearedcount = true
}

// CountCleared returns if the "count" edge to the UserCount entity was cleared.
func (m *UserMutation) CountCleared() bool {
	return m.clearedcount
}

// RemoveCountIDs removes the "count" edge to the UserCount entity by IDs.
func (m *UserMutation) RemoveCountIDs(ids ...int) {
	if m.removedcount == nil {
		m.removedcount = make(map[int]struct{})
	}
	for i := range ids {
		m.removedcount[ids[i]] = struct{}{}
	}
}

// RemovedCount returns the removed IDs of the "count" edge to the UserCount entity.
func (m *UserMutation) RemovedCountIDs() (ids []int) {
	for id := range m.removedcount {
		ids = append(ids, id)
	}
	return
}

// CountIDs returns the "count" edge IDs in the mutation.
func (m *UserMutation) CountIDs() (ids []int) {
	for id := range m.count {
		ids = append(ids, id)
	}
	return
}

// ResetCount resets all changes to the "count" edge.
func (m *UserMutation) ResetCount() {
	m.count = nil
	m.clearedcount = false
	m.removedcount = nil
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.phone != nil {
		fields = append(fields, user.FieldPhone)
	}
	if m.password != nil {
		fields = append(fields, user.FieldPassword)
	}
	if m.p_id != nil {
		fields = append(fields, user.FieldPID)
	}
	if m.invited_code != nil {
		fields = append(fields, user.FieldInvitedCode)
	}
	if m.created != nil {
		fields = append(fields, user.FieldCreated)
	}
	if m.updated != nil {
		fields = append(fields, user.FieldUpdated)
	}
	if m.deleted != nil {
		fields = append(fields, user.FieldDeleted)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldPhone:
		return m.Phone()
	case user.FieldPassword:
		return m.Password()
	case user.FieldPID:
		return m.PID()
	case user.FieldInvitedCode:
		return m.InvitedCode()
	case user.FieldCreated:
		return m.Created()
	case user.FieldUpdated:
		return m.Updated()
	case user.FieldDeleted:
		return m.Deleted()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldPhone:
		return m.OldPhone(ctx)
	case user.FieldPassword:
		return m.OldPassword(ctx)
	case user.FieldPID:
		return m.OldPID(ctx)
	case user.FieldInvitedCode:
		return m.OldInvitedCode(ctx)
	case user.FieldCreated:
		return m.OldCreated(ctx)
	case user.FieldUpdated:
		return m.OldUpdated(ctx)
	case user.FieldDeleted:
		return m.OldDeleted(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldPhone:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPhone(v)
		return nil
	case user.FieldPassword:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPassword(v)
		return nil
	case user.FieldPID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPID(v)
		return nil
	case user.FieldInvitedCode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInvitedCode(v)
		return nil
	case user.FieldCreated:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreated(v)
		return nil
	case user.FieldUpdated:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdated(v)
		return nil
	case user.FieldDeleted:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeleted(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	var fields []string
	if m.addp_id != nil {
		fields = append(fields, user.FieldPID)
	}
	if m.addcreated != nil {
		fields = append(fields, user.FieldCreated)
	}
	if m.addupdated != nil {
		fields = append(fields, user.FieldUpdated)
	}
	if m.adddeleted != nil {
		fields = append(fields, user.FieldDeleted)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case user.FieldPID:
		return m.AddedPID()
	case user.FieldCreated:
		return m.AddedCreated()
	case user.FieldUpdated:
		return m.AddedUpdated()
	case user.FieldDeleted:
		return m.AddedDeleted()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	case user.FieldPID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPID(v)
		return nil
	case user.FieldCreated:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCreated(v)
		return nil
	case user.FieldUpdated:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUpdated(v)
		return nil
	case user.FieldDeleted:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDeleted(v)
		return nil
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldPhone:
		m.ResetPhone()
		return nil
	case user.FieldPassword:
		m.ResetPassword()
		return nil
	case user.FieldPID:
		m.ResetPID()
		return nil
	case user.FieldInvitedCode:
		m.ResetInvitedCode()
		return nil
	case user.FieldCreated:
		m.ResetCreated()
		return nil
	case user.FieldUpdated:
		m.ResetUpdated()
		return nil
	case user.FieldDeleted:
		m.ResetDeleted()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.count != nil {
		edges = append(edges, user.EdgeCount)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeCount:
		ids := make([]ent.Value, 0, len(m.count))
		for id := range m.count {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedcount != nil {
		edges = append(edges, user.EdgeCount)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeCount:
		ids := make([]ent.Value, 0, len(m.removedcount))
		for id := range m.removedcount {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedcount {
		edges = append(edges, user.EdgeCount)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	case user.EdgeCount:
		return m.clearedcount
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case user.EdgeCount:
		m.ResetCount()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}

// UserCountMutation represents an operation that mutates the UserCount nodes in the graph.
type UserCountMutation struct {
	config
	op            Op
	typ           string
	id            *int
	self_buy      *float64
	addself_buy   *float64
	invite_buy    *float64
	addinvite_buy *float64
	level         *int
	addlevel      *int
	created       *int64
	addcreated    *int64
	updated       *int64
	addupdated    *int64
	deleted       *int64
	adddeleted    *int64
	clearedFields map[string]struct{}
	owner         *int64
	clearedowner  bool
	done          bool
	oldValue      func(context.Context) (*UserCount, error)
	predicates    []predicate.UserCount
}

var _ ent.Mutation = (*UserCountMutation)(nil)

// usercountOption allows management of the mutation configuration using functional options.
type usercountOption func(*UserCountMutation)

// newUserCountMutation creates new mutation for the UserCount entity.
func newUserCountMutation(c config, op Op, opts ...usercountOption) *UserCountMutation {
	m := &UserCountMutation{
		config:        c,
		op:            op,
		typ:           TypeUserCount,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserCountID sets the ID field of the mutation.
func withUserCountID(id int) usercountOption {
	return func(m *UserCountMutation) {
		var (
			err   error
			once  sync.Once
			value *UserCount
		)
		m.oldValue = func(ctx context.Context) (*UserCount, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().UserCount.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUserCount sets the old UserCount of the mutation.
func withUserCount(node *UserCount) usercountOption {
	return func(m *UserCountMutation) {
		m.oldValue = func(context.Context) (*UserCount, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserCountMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserCountMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID
// is only available if it was provided to the builder.
func (m *UserCountMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetSelfBuy sets the "self_buy" field.
func (m *UserCountMutation) SetSelfBuy(f float64) {
	m.self_buy = &f
	m.addself_buy = nil
}

// SelfBuy returns the value of the "self_buy" field in the mutation.
func (m *UserCountMutation) SelfBuy() (r float64, exists bool) {
	v := m.self_buy
	if v == nil {
		return
	}
	return *v, true
}

// OldSelfBuy returns the old "self_buy" field's value of the UserCount entity.
// If the UserCount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserCountMutation) OldSelfBuy(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldSelfBuy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldSelfBuy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSelfBuy: %w", err)
	}
	return oldValue.SelfBuy, nil
}

// AddSelfBuy adds f to the "self_buy" field.
func (m *UserCountMutation) AddSelfBuy(f float64) {
	if m.addself_buy != nil {
		*m.addself_buy += f
	} else {
		m.addself_buy = &f
	}
}

// AddedSelfBuy returns the value that was added to the "self_buy" field in this mutation.
func (m *UserCountMutation) AddedSelfBuy() (r float64, exists bool) {
	v := m.addself_buy
	if v == nil {
		return
	}
	return *v, true
}

// ResetSelfBuy resets all changes to the "self_buy" field.
func (m *UserCountMutation) ResetSelfBuy() {
	m.self_buy = nil
	m.addself_buy = nil
}

// SetInviteBuy sets the "invite_buy" field.
func (m *UserCountMutation) SetInviteBuy(f float64) {
	m.invite_buy = &f
	m.addinvite_buy = nil
}

// InviteBuy returns the value of the "invite_buy" field in the mutation.
func (m *UserCountMutation) InviteBuy() (r float64, exists bool) {
	v := m.invite_buy
	if v == nil {
		return
	}
	return *v, true
}

// OldInviteBuy returns the old "invite_buy" field's value of the UserCount entity.
// If the UserCount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserCountMutation) OldInviteBuy(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldInviteBuy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldInviteBuy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInviteBuy: %w", err)
	}
	return oldValue.InviteBuy, nil
}

// AddInviteBuy adds f to the "invite_buy" field.
func (m *UserCountMutation) AddInviteBuy(f float64) {
	if m.addinvite_buy != nil {
		*m.addinvite_buy += f
	} else {
		m.addinvite_buy = &f
	}
}

// AddedInviteBuy returns the value that was added to the "invite_buy" field in this mutation.
func (m *UserCountMutation) AddedInviteBuy() (r float64, exists bool) {
	v := m.addinvite_buy
	if v == nil {
		return
	}
	return *v, true
}

// ResetInviteBuy resets all changes to the "invite_buy" field.
func (m *UserCountMutation) ResetInviteBuy() {
	m.invite_buy = nil
	m.addinvite_buy = nil
}

// SetLevel sets the "level" field.
func (m *UserCountMutation) SetLevel(i int) {
	m.level = &i
	m.addlevel = nil
}

// Level returns the value of the "level" field in the mutation.
func (m *UserCountMutation) Level() (r int, exists bool) {
	v := m.level
	if v == nil {
		return
	}
	return *v, true
}

// OldLevel returns the old "level" field's value of the UserCount entity.
// If the UserCount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserCountMutation) OldLevel(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldLevel is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldLevel requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLevel: %w", err)
	}
	return oldValue.Level, nil
}

// AddLevel adds i to the "level" field.
func (m *UserCountMutation) AddLevel(i int) {
	if m.addlevel != nil {
		*m.addlevel += i
	} else {
		m.addlevel = &i
	}
}

// AddedLevel returns the value that was added to the "level" field in this mutation.
func (m *UserCountMutation) AddedLevel() (r int, exists bool) {
	v := m.addlevel
	if v == nil {
		return
	}
	return *v, true
}

// ResetLevel resets all changes to the "level" field.
func (m *UserCountMutation) ResetLevel() {
	m.level = nil
	m.addlevel = nil
}

// SetCreated sets the "created" field.
func (m *UserCountMutation) SetCreated(i int64) {
	m.created = &i
	m.addcreated = nil
}

// Created returns the value of the "created" field in the mutation.
func (m *UserCountMutation) Created() (r int64, exists bool) {
	v := m.created
	if v == nil {
		return
	}
	return *v, true
}

// OldCreated returns the old "created" field's value of the UserCount entity.
// If the UserCount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserCountMutation) OldCreated(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldCreated is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldCreated requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreated: %w", err)
	}
	return oldValue.Created, nil
}

// AddCreated adds i to the "created" field.
func (m *UserCountMutation) AddCreated(i int64) {
	if m.addcreated != nil {
		*m.addcreated += i
	} else {
		m.addcreated = &i
	}
}

// AddedCreated returns the value that was added to the "created" field in this mutation.
func (m *UserCountMutation) AddedCreated() (r int64, exists bool) {
	v := m.addcreated
	if v == nil {
		return
	}
	return *v, true
}

// ResetCreated resets all changes to the "created" field.
func (m *UserCountMutation) ResetCreated() {
	m.created = nil
	m.addcreated = nil
}

// SetUpdated sets the "updated" field.
func (m *UserCountMutation) SetUpdated(i int64) {
	m.updated = &i
	m.addupdated = nil
}

// Updated returns the value of the "updated" field in the mutation.
func (m *UserCountMutation) Updated() (r int64, exists bool) {
	v := m.updated
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdated returns the old "updated" field's value of the UserCount entity.
// If the UserCount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserCountMutation) OldUpdated(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldUpdated is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldUpdated requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdated: %w", err)
	}
	return oldValue.Updated, nil
}

// AddUpdated adds i to the "updated" field.
func (m *UserCountMutation) AddUpdated(i int64) {
	if m.addupdated != nil {
		*m.addupdated += i
	} else {
		m.addupdated = &i
	}
}

// AddedUpdated returns the value that was added to the "updated" field in this mutation.
func (m *UserCountMutation) AddedUpdated() (r int64, exists bool) {
	v := m.addupdated
	if v == nil {
		return
	}
	return *v, true
}

// ResetUpdated resets all changes to the "updated" field.
func (m *UserCountMutation) ResetUpdated() {
	m.updated = nil
	m.addupdated = nil
}

// SetDeleted sets the "deleted" field.
func (m *UserCountMutation) SetDeleted(i int64) {
	m.deleted = &i
	m.adddeleted = nil
}

// Deleted returns the value of the "deleted" field in the mutation.
func (m *UserCountMutation) Deleted() (r int64, exists bool) {
	v := m.deleted
	if v == nil {
		return
	}
	return *v, true
}

// OldDeleted returns the old "deleted" field's value of the UserCount entity.
// If the UserCount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserCountMutation) OldDeleted(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldDeleted is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldDeleted requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeleted: %w", err)
	}
	return oldValue.Deleted, nil
}

// AddDeleted adds i to the "deleted" field.
func (m *UserCountMutation) AddDeleted(i int64) {
	if m.adddeleted != nil {
		*m.adddeleted += i
	} else {
		m.adddeleted = &i
	}
}

// AddedDeleted returns the value that was added to the "deleted" field in this mutation.
func (m *UserCountMutation) AddedDeleted() (r int64, exists bool) {
	v := m.adddeleted
	if v == nil {
		return
	}
	return *v, true
}

// ResetDeleted resets all changes to the "deleted" field.
func (m *UserCountMutation) ResetDeleted() {
	m.deleted = nil
	m.adddeleted = nil
}

// SetOwnerID sets the "owner" edge to the User entity by id.
func (m *UserCountMutation) SetOwnerID(id int64) {
	m.owner = &id
}

// ClearOwner clears the "owner" edge to the User entity.
func (m *UserCountMutation) ClearOwner() {
	m.clearedowner = true
}

// OwnerCleared returns if the "owner" edge to the User entity was cleared.
func (m *UserCountMutation) OwnerCleared() bool {
	return m.clearedowner
}

// OwnerID returns the "owner" edge ID in the mutation.
func (m *UserCountMutation) OwnerID() (id int64, exists bool) {
	if m.owner != nil {
		return *m.owner, true
	}
	return
}

// OwnerIDs returns the "owner" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// OwnerID instead. It exists only for internal usage by the builders.
func (m *UserCountMutation) OwnerIDs() (ids []int64) {
	if id := m.owner; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetOwner resets all changes to the "owner" edge.
func (m *UserCountMutation) ResetOwner() {
	m.owner = nil
	m.clearedowner = false
}

// Op returns the operation name.
func (m *UserCountMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (UserCount).
func (m *UserCountMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserCountMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.self_buy != nil {
		fields = append(fields, usercount.FieldSelfBuy)
	}
	if m.invite_buy != nil {
		fields = append(fields, usercount.FieldInviteBuy)
	}
	if m.level != nil {
		fields = append(fields, usercount.FieldLevel)
	}
	if m.created != nil {
		fields = append(fields, usercount.FieldCreated)
	}
	if m.updated != nil {
		fields = append(fields, usercount.FieldUpdated)
	}
	if m.deleted != nil {
		fields = append(fields, usercount.FieldDeleted)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserCountMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case usercount.FieldSelfBuy:
		return m.SelfBuy()
	case usercount.FieldInviteBuy:
		return m.InviteBuy()
	case usercount.FieldLevel:
		return m.Level()
	case usercount.FieldCreated:
		return m.Created()
	case usercount.FieldUpdated:
		return m.Updated()
	case usercount.FieldDeleted:
		return m.Deleted()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserCountMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case usercount.FieldSelfBuy:
		return m.OldSelfBuy(ctx)
	case usercount.FieldInviteBuy:
		return m.OldInviteBuy(ctx)
	case usercount.FieldLevel:
		return m.OldLevel(ctx)
	case usercount.FieldCreated:
		return m.OldCreated(ctx)
	case usercount.FieldUpdated:
		return m.OldUpdated(ctx)
	case usercount.FieldDeleted:
		return m.OldDeleted(ctx)
	}
	return nil, fmt.Errorf("unknown UserCount field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserCountMutation) SetField(name string, value ent.Value) error {
	switch name {
	case usercount.FieldSelfBuy:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSelfBuy(v)
		return nil
	case usercount.FieldInviteBuy:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInviteBuy(v)
		return nil
	case usercount.FieldLevel:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLevel(v)
		return nil
	case usercount.FieldCreated:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreated(v)
		return nil
	case usercount.FieldUpdated:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdated(v)
		return nil
	case usercount.FieldDeleted:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeleted(v)
		return nil
	}
	return fmt.Errorf("unknown UserCount field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserCountMutation) AddedFields() []string {
	var fields []string
	if m.addself_buy != nil {
		fields = append(fields, usercount.FieldSelfBuy)
	}
	if m.addinvite_buy != nil {
		fields = append(fields, usercount.FieldInviteBuy)
	}
	if m.addlevel != nil {
		fields = append(fields, usercount.FieldLevel)
	}
	if m.addcreated != nil {
		fields = append(fields, usercount.FieldCreated)
	}
	if m.addupdated != nil {
		fields = append(fields, usercount.FieldUpdated)
	}
	if m.adddeleted != nil {
		fields = append(fields, usercount.FieldDeleted)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserCountMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case usercount.FieldSelfBuy:
		return m.AddedSelfBuy()
	case usercount.FieldInviteBuy:
		return m.AddedInviteBuy()
	case usercount.FieldLevel:
		return m.AddedLevel()
	case usercount.FieldCreated:
		return m.AddedCreated()
	case usercount.FieldUpdated:
		return m.AddedUpdated()
	case usercount.FieldDeleted:
		return m.AddedDeleted()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserCountMutation) AddField(name string, value ent.Value) error {
	switch name {
	case usercount.FieldSelfBuy:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSelfBuy(v)
		return nil
	case usercount.FieldInviteBuy:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddInviteBuy(v)
		return nil
	case usercount.FieldLevel:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddLevel(v)
		return nil
	case usercount.FieldCreated:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCreated(v)
		return nil
	case usercount.FieldUpdated:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUpdated(v)
		return nil
	case usercount.FieldDeleted:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDeleted(v)
		return nil
	}
	return fmt.Errorf("unknown UserCount numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserCountMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserCountMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserCountMutation) ClearField(name string) error {
	return fmt.Errorf("unknown UserCount nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserCountMutation) ResetField(name string) error {
	switch name {
	case usercount.FieldSelfBuy:
		m.ResetSelfBuy()
		return nil
	case usercount.FieldInviteBuy:
		m.ResetInviteBuy()
		return nil
	case usercount.FieldLevel:
		m.ResetLevel()
		return nil
	case usercount.FieldCreated:
		m.ResetCreated()
		return nil
	case usercount.FieldUpdated:
		m.ResetUpdated()
		return nil
	case usercount.FieldDeleted:
		m.ResetDeleted()
		return nil
	}
	return fmt.Errorf("unknown UserCount field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserCountMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.owner != nil {
		edges = append(edges, usercount.EdgeOwner)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserCountMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case usercount.EdgeOwner:
		if id := m.owner; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserCountMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserCountMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserCountMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedowner {
		edges = append(edges, usercount.EdgeOwner)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserCountMutation) EdgeCleared(name string) bool {
	switch name {
	case usercount.EdgeOwner:
		return m.clearedowner
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserCountMutation) ClearEdge(name string) error {
	switch name {
	case usercount.EdgeOwner:
		m.ClearOwner()
		return nil
	}
	return fmt.Errorf("unknown UserCount unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserCountMutation) ResetEdge(name string) error {
	switch name {
	case usercount.EdgeOwner:
		m.ResetOwner()
		return nil
	}
	return fmt.Errorf("unknown UserCount edge %s", name)
}
