// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"sqlent/ent/predicate"
	"sqlent/ent/userbuyrecord"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserBuyRecordDelete is the builder for deleting a UserBuyRecord entity.
type UserBuyRecordDelete struct {
	config
	hooks    []Hook
	mutation *UserBuyRecordMutation
}

// Where adds a new predicate to the UserBuyRecordDelete builder.
func (ubrd *UserBuyRecordDelete) Where(ps ...predicate.UserBuyRecord) *UserBuyRecordDelete {
	ubrd.mutation.predicates = append(ubrd.mutation.predicates, ps...)
	return ubrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ubrd *UserBuyRecordDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ubrd.hooks) == 0 {
		affected, err = ubrd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserBuyRecordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ubrd.mutation = mutation
			affected, err = ubrd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ubrd.hooks) - 1; i >= 0; i-- {
			mut = ubrd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ubrd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ubrd *UserBuyRecordDelete) ExecX(ctx context.Context) int {
	n, err := ubrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ubrd *UserBuyRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: userbuyrecord.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: userbuyrecord.FieldID,
			},
		},
	}
	if ps := ubrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ubrd.driver, _spec)
}

// UserBuyRecordDeleteOne is the builder for deleting a single UserBuyRecord entity.
type UserBuyRecordDeleteOne struct {
	ubrd *UserBuyRecordDelete
}

// Exec executes the deletion query.
func (ubrdo *UserBuyRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := ubrdo.ubrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userbuyrecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ubrdo *UserBuyRecordDeleteOne) ExecX(ctx context.Context) {
	ubrdo.ubrd.ExecX(ctx)
}
