// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"sqlent/ent/predicate"
	"sqlent/ent/user"
	"sqlent/ent/usercount"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserCountQuery is the builder for querying UserCount entities.
type UserCountQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserCount
	// eager-loading edges.
	withOwner *UserQuery
	withFKs   bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserCountQuery builder.
func (ucq *UserCountQuery) Where(ps ...predicate.UserCount) *UserCountQuery {
	ucq.predicates = append(ucq.predicates, ps...)
	return ucq
}

// Limit adds a limit step to the query.
func (ucq *UserCountQuery) Limit(limit int) *UserCountQuery {
	ucq.limit = &limit
	return ucq
}

// Offset adds an offset step to the query.
func (ucq *UserCountQuery) Offset(offset int) *UserCountQuery {
	ucq.offset = &offset
	return ucq
}

// Order adds an order step to the query.
func (ucq *UserCountQuery) Order(o ...OrderFunc) *UserCountQuery {
	ucq.order = append(ucq.order, o...)
	return ucq
}

// QueryOwner chains the current query on the "owner" edge.
func (ucq *UserCountQuery) QueryOwner() *UserQuery {
	query := &UserQuery{config: ucq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ucq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ucq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usercount.Table, usercount.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, usercount.OwnerTable, usercount.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(ucq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserCount entity from the query.
// Returns a *NotFoundError when no UserCount was found.
func (ucq *UserCountQuery) First(ctx context.Context) (*UserCount, error) {
	nodes, err := ucq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usercount.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ucq *UserCountQuery) FirstX(ctx context.Context) *UserCount {
	node, err := ucq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserCount ID from the query.
// Returns a *NotFoundError when no UserCount ID was found.
func (ucq *UserCountQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ucq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usercount.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ucq *UserCountQuery) FirstIDX(ctx context.Context) int {
	id, err := ucq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserCount entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one UserCount entity is not found.
// Returns a *NotFoundError when no UserCount entities are found.
func (ucq *UserCountQuery) Only(ctx context.Context) (*UserCount, error) {
	nodes, err := ucq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usercount.Label}
	default:
		return nil, &NotSingularError{usercount.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ucq *UserCountQuery) OnlyX(ctx context.Context) *UserCount {
	node, err := ucq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserCount ID in the query.
// Returns a *NotSingularError when exactly one UserCount ID is not found.
// Returns a *NotFoundError when no entities are found.
func (ucq *UserCountQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ucq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usercount.Label}
	default:
		err = &NotSingularError{usercount.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ucq *UserCountQuery) OnlyIDX(ctx context.Context) int {
	id, err := ucq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserCounts.
func (ucq *UserCountQuery) All(ctx context.Context) ([]*UserCount, error) {
	if err := ucq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ucq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ucq *UserCountQuery) AllX(ctx context.Context) []*UserCount {
	nodes, err := ucq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserCount IDs.
func (ucq *UserCountQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ucq.Select(usercount.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ucq *UserCountQuery) IDsX(ctx context.Context) []int {
	ids, err := ucq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ucq *UserCountQuery) Count(ctx context.Context) (int, error) {
	if err := ucq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ucq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ucq *UserCountQuery) CountX(ctx context.Context) int {
	count, err := ucq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ucq *UserCountQuery) Exist(ctx context.Context) (bool, error) {
	if err := ucq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ucq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ucq *UserCountQuery) ExistX(ctx context.Context) bool {
	exist, err := ucq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserCountQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ucq *UserCountQuery) Clone() *UserCountQuery {
	if ucq == nil {
		return nil
	}
	return &UserCountQuery{
		config:     ucq.config,
		limit:      ucq.limit,
		offset:     ucq.offset,
		order:      append([]OrderFunc{}, ucq.order...),
		predicates: append([]predicate.UserCount{}, ucq.predicates...),
		withOwner:  ucq.withOwner.Clone(),
		// clone intermediate query.
		sql:  ucq.sql.Clone(),
		path: ucq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (ucq *UserCountQuery) WithOwner(opts ...func(*UserQuery)) *UserCountQuery {
	query := &UserQuery{config: ucq.config}
	for _, opt := range opts {
		opt(query)
	}
	ucq.withOwner = query
	return ucq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SelfBuy float64 `json:"self_buy,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserCount.Query().
//		GroupBy(usercount.FieldSelfBuy).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ucq *UserCountQuery) GroupBy(field string, fields ...string) *UserCountGroupBy {
	group := &UserCountGroupBy{config: ucq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ucq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ucq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SelfBuy float64 `json:"self_buy,omitempty"`
//	}
//
//	client.UserCount.Query().
//		Select(usercount.FieldSelfBuy).
//		Scan(ctx, &v)
//
func (ucq *UserCountQuery) Select(field string, fields ...string) *UserCountSelect {
	ucq.fields = append([]string{field}, fields...)
	return &UserCountSelect{UserCountQuery: ucq}
}

func (ucq *UserCountQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ucq.fields {
		if !usercount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ucq.path != nil {
		prev, err := ucq.path(ctx)
		if err != nil {
			return err
		}
		ucq.sql = prev
	}
	return nil
}

func (ucq *UserCountQuery) sqlAll(ctx context.Context) ([]*UserCount, error) {
	var (
		nodes       = []*UserCount{}
		withFKs     = ucq.withFKs
		_spec       = ucq.querySpec()
		loadedTypes = [1]bool{
			ucq.withOwner != nil,
		}
	)
	if ucq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, usercount.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &UserCount{config: ucq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ucq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := ucq.withOwner; query != nil {
		ids := make([]int64, 0, len(nodes))
		nodeids := make(map[int64][]*UserCount)
		for i := range nodes {
			fk := nodes[i].user_id
			if fk != nil {
				ids = append(ids, *fk)
				nodeids[*fk] = append(nodeids[*fk], nodes[i])
			}
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Owner = n
			}
		}
	}

	return nodes, nil
}

func (ucq *UserCountQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ucq.querySpec()
	return sqlgraph.CountNodes(ctx, ucq.driver, _spec)
}

func (ucq *UserCountQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ucq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ucq *UserCountQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usercount.Table,
			Columns: usercount.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usercount.FieldID,
			},
		},
		From:   ucq.sql,
		Unique: true,
	}
	if fields := ucq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usercount.FieldID)
		for i := range fields {
			if fields[i] != usercount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ucq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ucq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ucq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ucq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, usercount.ValidColumn)
			}
		}
	}
	return _spec
}

func (ucq *UserCountQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ucq.driver.Dialect())
	t1 := builder.Table(usercount.Table)
	selector := builder.Select(t1.Columns(usercount.Columns...)...).From(t1)
	if ucq.sql != nil {
		selector = ucq.sql
		selector.Select(selector.Columns(usercount.Columns...)...)
	}
	for _, p := range ucq.predicates {
		p(selector)
	}
	for _, p := range ucq.order {
		p(selector, usercount.ValidColumn)
	}
	if offset := ucq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ucq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserCountGroupBy is the group-by builder for UserCount entities.
type UserCountGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ucgb *UserCountGroupBy) Aggregate(fns ...AggregateFunc) *UserCountGroupBy {
	ucgb.fns = append(ucgb.fns, fns...)
	return ucgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ucgb *UserCountGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ucgb.path(ctx)
	if err != nil {
		return err
	}
	ucgb.sql = query
	return ucgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ucgb *UserCountGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ucgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (ucgb *UserCountGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ucgb.fields) > 1 {
		return nil, errors.New("ent: UserCountGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ucgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ucgb *UserCountGroupBy) StringsX(ctx context.Context) []string {
	v, err := ucgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ucgb *UserCountGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ucgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usercount.Label}
	default:
		err = fmt.Errorf("ent: UserCountGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ucgb *UserCountGroupBy) StringX(ctx context.Context) string {
	v, err := ucgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (ucgb *UserCountGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ucgb.fields) > 1 {
		return nil, errors.New("ent: UserCountGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ucgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ucgb *UserCountGroupBy) IntsX(ctx context.Context) []int {
	v, err := ucgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ucgb *UserCountGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ucgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usercount.Label}
	default:
		err = fmt.Errorf("ent: UserCountGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ucgb *UserCountGroupBy) IntX(ctx context.Context) int {
	v, err := ucgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ucgb *UserCountGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ucgb.fields) > 1 {
		return nil, errors.New("ent: UserCountGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ucgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ucgb *UserCountGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ucgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ucgb *UserCountGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ucgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usercount.Label}
	default:
		err = fmt.Errorf("ent: UserCountGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ucgb *UserCountGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ucgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (ucgb *UserCountGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ucgb.fields) > 1 {
		return nil, errors.New("ent: UserCountGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ucgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ucgb *UserCountGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ucgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ucgb *UserCountGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ucgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usercount.Label}
	default:
		err = fmt.Errorf("ent: UserCountGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ucgb *UserCountGroupBy) BoolX(ctx context.Context) bool {
	v, err := ucgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ucgb *UserCountGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ucgb.fields {
		if !usercount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ucgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ucgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ucgb *UserCountGroupBy) sqlQuery() *sql.Selector {
	selector := ucgb.sql
	columns := make([]string, 0, len(ucgb.fields)+len(ucgb.fns))
	columns = append(columns, ucgb.fields...)
	for _, fn := range ucgb.fns {
		columns = append(columns, fn(selector, usercount.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(ucgb.fields...)
}

// UserCountSelect is the builder for selecting fields of UserCount entities.
type UserCountSelect struct {
	*UserCountQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ucs *UserCountSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ucs.prepareQuery(ctx); err != nil {
		return err
	}
	ucs.sql = ucs.UserCountQuery.sqlQuery(ctx)
	return ucs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ucs *UserCountSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ucs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ucs *UserCountSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ucs.fields) > 1 {
		return nil, errors.New("ent: UserCountSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ucs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ucs *UserCountSelect) StringsX(ctx context.Context) []string {
	v, err := ucs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ucs *UserCountSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ucs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usercount.Label}
	default:
		err = fmt.Errorf("ent: UserCountSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ucs *UserCountSelect) StringX(ctx context.Context) string {
	v, err := ucs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ucs *UserCountSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ucs.fields) > 1 {
		return nil, errors.New("ent: UserCountSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ucs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ucs *UserCountSelect) IntsX(ctx context.Context) []int {
	v, err := ucs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ucs *UserCountSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ucs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usercount.Label}
	default:
		err = fmt.Errorf("ent: UserCountSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ucs *UserCountSelect) IntX(ctx context.Context) int {
	v, err := ucs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ucs *UserCountSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ucs.fields) > 1 {
		return nil, errors.New("ent: UserCountSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ucs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ucs *UserCountSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ucs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ucs *UserCountSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ucs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usercount.Label}
	default:
		err = fmt.Errorf("ent: UserCountSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ucs *UserCountSelect) Float64X(ctx context.Context) float64 {
	v, err := ucs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ucs *UserCountSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ucs.fields) > 1 {
		return nil, errors.New("ent: UserCountSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ucs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ucs *UserCountSelect) BoolsX(ctx context.Context) []bool {
	v, err := ucs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ucs *UserCountSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ucs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usercount.Label}
	default:
		err = fmt.Errorf("ent: UserCountSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ucs *UserCountSelect) BoolX(ctx context.Context) bool {
	v, err := ucs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ucs *UserCountSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ucs.sqlQuery().Query()
	if err := ucs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ucs *UserCountSelect) sqlQuery() sql.Querier {
	selector := ucs.sql
	selector.Select(selector.Columns(ucs.fields...)...)
	return selector
}
