// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"sqlent/ent/predicate"
	"sqlent/ent/user"
	"sqlent/ent/userbuyrecord"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserBuyRecordQuery is the builder for querying UserBuyRecord entities.
type UserBuyRecordQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserBuyRecord
	// eager-loading edges.
	withOwner *UserQuery
	withFKs   bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserBuyRecordQuery builder.
func (ubrq *UserBuyRecordQuery) Where(ps ...predicate.UserBuyRecord) *UserBuyRecordQuery {
	ubrq.predicates = append(ubrq.predicates, ps...)
	return ubrq
}

// Limit adds a limit step to the query.
func (ubrq *UserBuyRecordQuery) Limit(limit int) *UserBuyRecordQuery {
	ubrq.limit = &limit
	return ubrq
}

// Offset adds an offset step to the query.
func (ubrq *UserBuyRecordQuery) Offset(offset int) *UserBuyRecordQuery {
	ubrq.offset = &offset
	return ubrq
}

// Order adds an order step to the query.
func (ubrq *UserBuyRecordQuery) Order(o ...OrderFunc) *UserBuyRecordQuery {
	ubrq.order = append(ubrq.order, o...)
	return ubrq
}

// QueryOwner chains the current query on the "owner" edge.
func (ubrq *UserBuyRecordQuery) QueryOwner() *UserQuery {
	query := &UserQuery{config: ubrq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ubrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ubrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userbuyrecord.Table, userbuyrecord.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, userbuyrecord.OwnerTable, userbuyrecord.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(ubrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserBuyRecord entity from the query.
// Returns a *NotFoundError when no UserBuyRecord was found.
func (ubrq *UserBuyRecordQuery) First(ctx context.Context) (*UserBuyRecord, error) {
	nodes, err := ubrq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userbuyrecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ubrq *UserBuyRecordQuery) FirstX(ctx context.Context) *UserBuyRecord {
	node, err := ubrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserBuyRecord ID from the query.
// Returns a *NotFoundError when no UserBuyRecord ID was found.
func (ubrq *UserBuyRecordQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ubrq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userbuyrecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ubrq *UserBuyRecordQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := ubrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserBuyRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one UserBuyRecord entity is not found.
// Returns a *NotFoundError when no UserBuyRecord entities are found.
func (ubrq *UserBuyRecordQuery) Only(ctx context.Context) (*UserBuyRecord, error) {
	nodes, err := ubrq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userbuyrecord.Label}
	default:
		return nil, &NotSingularError{userbuyrecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ubrq *UserBuyRecordQuery) OnlyX(ctx context.Context) *UserBuyRecord {
	node, err := ubrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserBuyRecord ID in the query.
// Returns a *NotSingularError when exactly one UserBuyRecord ID is not found.
// Returns a *NotFoundError when no entities are found.
func (ubrq *UserBuyRecordQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ubrq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userbuyrecord.Label}
	default:
		err = &NotSingularError{userbuyrecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ubrq *UserBuyRecordQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := ubrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserBuyRecords.
func (ubrq *UserBuyRecordQuery) All(ctx context.Context) ([]*UserBuyRecord, error) {
	if err := ubrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ubrq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ubrq *UserBuyRecordQuery) AllX(ctx context.Context) []*UserBuyRecord {
	nodes, err := ubrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserBuyRecord IDs.
func (ubrq *UserBuyRecordQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := ubrq.Select(userbuyrecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ubrq *UserBuyRecordQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := ubrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ubrq *UserBuyRecordQuery) Count(ctx context.Context) (int, error) {
	if err := ubrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ubrq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ubrq *UserBuyRecordQuery) CountX(ctx context.Context) int {
	count, err := ubrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ubrq *UserBuyRecordQuery) Exist(ctx context.Context) (bool, error) {
	if err := ubrq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ubrq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ubrq *UserBuyRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := ubrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserBuyRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ubrq *UserBuyRecordQuery) Clone() *UserBuyRecordQuery {
	if ubrq == nil {
		return nil
	}
	return &UserBuyRecordQuery{
		config:     ubrq.config,
		limit:      ubrq.limit,
		offset:     ubrq.offset,
		order:      append([]OrderFunc{}, ubrq.order...),
		predicates: append([]predicate.UserBuyRecord{}, ubrq.predicates...),
		withOwner:  ubrq.withOwner.Clone(),
		// clone intermediate query.
		sql:  ubrq.sql.Clone(),
		path: ubrq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (ubrq *UserBuyRecordQuery) WithOwner(opts ...func(*UserQuery)) *UserBuyRecordQuery {
	query := &UserQuery{config: ubrq.config}
	for _, opt := range opts {
		opt(query)
	}
	ubrq.withOwner = query
	return ubrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Power int `json:"power,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserBuyRecord.Query().
//		GroupBy(userbuyrecord.FieldPower).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ubrq *UserBuyRecordQuery) GroupBy(field string, fields ...string) *UserBuyRecordGroupBy {
	group := &UserBuyRecordGroupBy{config: ubrq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ubrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ubrq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Power int `json:"power,omitempty"`
//	}
//
//	client.UserBuyRecord.Query().
//		Select(userbuyrecord.FieldPower).
//		Scan(ctx, &v)
//
func (ubrq *UserBuyRecordQuery) Select(field string, fields ...string) *UserBuyRecordSelect {
	ubrq.fields = append([]string{field}, fields...)
	return &UserBuyRecordSelect{UserBuyRecordQuery: ubrq}
}

func (ubrq *UserBuyRecordQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ubrq.fields {
		if !userbuyrecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ubrq.path != nil {
		prev, err := ubrq.path(ctx)
		if err != nil {
			return err
		}
		ubrq.sql = prev
	}
	return nil
}

func (ubrq *UserBuyRecordQuery) sqlAll(ctx context.Context) ([]*UserBuyRecord, error) {
	var (
		nodes       = []*UserBuyRecord{}
		withFKs     = ubrq.withFKs
		_spec       = ubrq.querySpec()
		loadedTypes = [1]bool{
			ubrq.withOwner != nil,
		}
	)
	if ubrq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, userbuyrecord.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &UserBuyRecord{config: ubrq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ubrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := ubrq.withOwner; query != nil {
		ids := make([]int64, 0, len(nodes))
		nodeids := make(map[int64][]*UserBuyRecord)
		for i := range nodes {
			fk := nodes[i].user_id
			if fk != nil {
				ids = append(ids, *fk)
				nodeids[*fk] = append(nodeids[*fk], nodes[i])
			}
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Owner = n
			}
		}
	}

	return nodes, nil
}

func (ubrq *UserBuyRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ubrq.querySpec()
	return sqlgraph.CountNodes(ctx, ubrq.driver, _spec)
}

func (ubrq *UserBuyRecordQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ubrq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ubrq *UserBuyRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userbuyrecord.Table,
			Columns: userbuyrecord.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: userbuyrecord.FieldID,
			},
		},
		From:   ubrq.sql,
		Unique: true,
	}
	if fields := ubrq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userbuyrecord.FieldID)
		for i := range fields {
			if fields[i] != userbuyrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ubrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ubrq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ubrq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ubrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, userbuyrecord.ValidColumn)
			}
		}
	}
	return _spec
}

func (ubrq *UserBuyRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ubrq.driver.Dialect())
	t1 := builder.Table(userbuyrecord.Table)
	selector := builder.Select(t1.Columns(userbuyrecord.Columns...)...).From(t1)
	if ubrq.sql != nil {
		selector = ubrq.sql
		selector.Select(selector.Columns(userbuyrecord.Columns...)...)
	}
	for _, p := range ubrq.predicates {
		p(selector)
	}
	for _, p := range ubrq.order {
		p(selector, userbuyrecord.ValidColumn)
	}
	if offset := ubrq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ubrq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserBuyRecordGroupBy is the group-by builder for UserBuyRecord entities.
type UserBuyRecordGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ubrgb *UserBuyRecordGroupBy) Aggregate(fns ...AggregateFunc) *UserBuyRecordGroupBy {
	ubrgb.fns = append(ubrgb.fns, fns...)
	return ubrgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ubrgb *UserBuyRecordGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ubrgb.path(ctx)
	if err != nil {
		return err
	}
	ubrgb.sql = query
	return ubrgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ubrgb *UserBuyRecordGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ubrgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (ubrgb *UserBuyRecordGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ubrgb.fields) > 1 {
		return nil, errors.New("ent: UserBuyRecordGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ubrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ubrgb *UserBuyRecordGroupBy) StringsX(ctx context.Context) []string {
	v, err := ubrgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ubrgb *UserBuyRecordGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ubrgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userbuyrecord.Label}
	default:
		err = fmt.Errorf("ent: UserBuyRecordGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ubrgb *UserBuyRecordGroupBy) StringX(ctx context.Context) string {
	v, err := ubrgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (ubrgb *UserBuyRecordGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ubrgb.fields) > 1 {
		return nil, errors.New("ent: UserBuyRecordGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ubrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ubrgb *UserBuyRecordGroupBy) IntsX(ctx context.Context) []int {
	v, err := ubrgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ubrgb *UserBuyRecordGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ubrgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userbuyrecord.Label}
	default:
		err = fmt.Errorf("ent: UserBuyRecordGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ubrgb *UserBuyRecordGroupBy) IntX(ctx context.Context) int {
	v, err := ubrgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ubrgb *UserBuyRecordGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ubrgb.fields) > 1 {
		return nil, errors.New("ent: UserBuyRecordGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ubrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ubrgb *UserBuyRecordGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ubrgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ubrgb *UserBuyRecordGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ubrgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userbuyrecord.Label}
	default:
		err = fmt.Errorf("ent: UserBuyRecordGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ubrgb *UserBuyRecordGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ubrgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (ubrgb *UserBuyRecordGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ubrgb.fields) > 1 {
		return nil, errors.New("ent: UserBuyRecordGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ubrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ubrgb *UserBuyRecordGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ubrgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ubrgb *UserBuyRecordGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ubrgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userbuyrecord.Label}
	default:
		err = fmt.Errorf("ent: UserBuyRecordGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ubrgb *UserBuyRecordGroupBy) BoolX(ctx context.Context) bool {
	v, err := ubrgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ubrgb *UserBuyRecordGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ubrgb.fields {
		if !userbuyrecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ubrgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ubrgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ubrgb *UserBuyRecordGroupBy) sqlQuery() *sql.Selector {
	selector := ubrgb.sql
	columns := make([]string, 0, len(ubrgb.fields)+len(ubrgb.fns))
	columns = append(columns, ubrgb.fields...)
	for _, fn := range ubrgb.fns {
		columns = append(columns, fn(selector, userbuyrecord.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(ubrgb.fields...)
}

// UserBuyRecordSelect is the builder for selecting fields of UserBuyRecord entities.
type UserBuyRecordSelect struct {
	*UserBuyRecordQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ubrs *UserBuyRecordSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ubrs.prepareQuery(ctx); err != nil {
		return err
	}
	ubrs.sql = ubrs.UserBuyRecordQuery.sqlQuery(ctx)
	return ubrs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ubrs *UserBuyRecordSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ubrs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ubrs *UserBuyRecordSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ubrs.fields) > 1 {
		return nil, errors.New("ent: UserBuyRecordSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ubrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ubrs *UserBuyRecordSelect) StringsX(ctx context.Context) []string {
	v, err := ubrs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ubrs *UserBuyRecordSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ubrs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userbuyrecord.Label}
	default:
		err = fmt.Errorf("ent: UserBuyRecordSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ubrs *UserBuyRecordSelect) StringX(ctx context.Context) string {
	v, err := ubrs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ubrs *UserBuyRecordSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ubrs.fields) > 1 {
		return nil, errors.New("ent: UserBuyRecordSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ubrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ubrs *UserBuyRecordSelect) IntsX(ctx context.Context) []int {
	v, err := ubrs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ubrs *UserBuyRecordSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ubrs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userbuyrecord.Label}
	default:
		err = fmt.Errorf("ent: UserBuyRecordSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ubrs *UserBuyRecordSelect) IntX(ctx context.Context) int {
	v, err := ubrs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ubrs *UserBuyRecordSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ubrs.fields) > 1 {
		return nil, errors.New("ent: UserBuyRecordSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ubrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ubrs *UserBuyRecordSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ubrs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ubrs *UserBuyRecordSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ubrs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userbuyrecord.Label}
	default:
		err = fmt.Errorf("ent: UserBuyRecordSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ubrs *UserBuyRecordSelect) Float64X(ctx context.Context) float64 {
	v, err := ubrs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ubrs *UserBuyRecordSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ubrs.fields) > 1 {
		return nil, errors.New("ent: UserBuyRecordSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ubrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ubrs *UserBuyRecordSelect) BoolsX(ctx context.Context) []bool {
	v, err := ubrs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ubrs *UserBuyRecordSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ubrs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userbuyrecord.Label}
	default:
		err = fmt.Errorf("ent: UserBuyRecordSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ubrs *UserBuyRecordSelect) BoolX(ctx context.Context) bool {
	v, err := ubrs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ubrs *UserBuyRecordSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ubrs.sqlQuery().Query()
	if err := ubrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ubrs *UserBuyRecordSelect) sqlQuery() sql.Querier {
	selector := ubrs.sql
	selector.Select(selector.Columns(ubrs.fields...)...)
	return selector
}
