// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserCount is the predicate function for usercount builders.
type UserCount func(*sql.Selector)
