// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "phone", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "p_id", Type: field.TypeInt, Default: 0},
		{Name: "invited_code", Type: field.TypeString},
		{Name: "created", Type: field.TypeInt64, Default: 1616407968},
		{Name: "updated", Type: field.TypeInt64, Default: 0},
		{Name: "deleted", Type: field.TypeInt64, Default: 0},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:        "users",
		Columns:     UsersColumns,
		PrimaryKey:  []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// UserCountsColumns holds the columns for the "user_counts" table.
	UserCountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "self_buy", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"mysql": "decimal(18,8)"}},
		{Name: "invite_buy", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"mysql": "decimal(18,8)"}},
		{Name: "level", Type: field.TypeInt, Default: 0},
		{Name: "created", Type: field.TypeInt64, Default: 1616407968},
		{Name: "updated", Type: field.TypeInt64, Default: 0},
		{Name: "deleted", Type: field.TypeInt64, Default: 0},
		{Name: "user_id", Type: field.TypeInt64, Nullable: true},
	}
	// UserCountsTable holds the schema information for the "user_counts" table.
	UserCountsTable = &schema.Table{
		Name:       "user_counts",
		Columns:    UserCountsColumns,
		PrimaryKey: []*schema.Column{UserCountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_counts_users_count",
				Columns:    []*schema.Column{UserCountsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
		UserCountsTable,
	}
)

func init() {
	UserCountsTable.ForeignKeys[0].RefTable = UsersTable
}
