// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldPID holds the string denoting the p_id field in the database.
	FieldPID = "p_id"
	// FieldInvitedCode holds the string denoting the invited_code field in the database.
	FieldInvitedCode = "invited_code"
	// FieldCreated holds the string denoting the created field in the database.
	FieldCreated = "created"
	// FieldUpdated holds the string denoting the updated field in the database.
	FieldUpdated = "updated"
	// FieldDeleted holds the string denoting the deleted field in the database.
	FieldDeleted = "deleted"
	// EdgeCount holds the string denoting the count edge name in mutations.
	EdgeCount = "count"
	// Table holds the table name of the user in the database.
	Table = "users"
	// CountTable is the table the holds the count relation/edge.
	CountTable = "user_counts"
	// CountInverseTable is the table name for the UserCount entity.
	// It exists in this package in order to avoid circular dependency with the "usercount" package.
	CountInverseTable = "user_counts"
	// CountColumn is the table column denoting the count relation/edge.
	CountColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldPhone,
	FieldPassword,
	FieldPID,
	FieldInvitedCode,
	FieldCreated,
	FieldUpdated,
	FieldDeleted,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	PhoneValidator func(string) error
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
	// DefaultPID holds the default value on creation for the "p_id" field.
	DefaultPID int
	// InvitedCodeValidator is a validator for the "invited_code" field. It is called by the builders before save.
	InvitedCodeValidator func(string) error
	// DefaultCreated holds the default value on creation for the "created" field.
	DefaultCreated int64
	// DefaultUpdated holds the default value on creation for the "updated" field.
	DefaultUpdated int64
	// DefaultDeleted holds the default value on creation for the "deleted" field.
	DefaultDeleted int64
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)
