[package]
name = "first_cmd"
version = "0.1.0"
authors = ["董家宏 <dongjiahong@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.32"
