config_path = "./config.yml" # machinery的配置文件
app_port = 18888 # gin的对外端口

task_redis_host = "localhost"
task_redis_port = 6379
task_redis_password = ""
task_redis_db = 0
task_redis_pool_size = 20 # redis线程池大小
